site_name: Ngiridb
site_description: Mult Async database for Python.

theme:
    name: 'material'

repo_name: pesaply/ngiridb
repo_url: https://github.com/pesaply/ngiridb
# edit_uri: ""

nav:
    - Introduction: 'index.md'
    - Database Queries: 'database_queries.md'
    - Connections & Transactions: 'connections_and_transactions.md'
    - Tests & Migrations: 'tests_and_migrations.md'
    - Contributing: 'contributing.md'

markdown_extensions:
  - mkautodoc
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
